"""
Scenarios for day {day}
"""

from common.scenario import Scenario

input="""............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
output="14"
scenario = Scenario(input, output)
part_01_scenarios = [scenario]

input="""............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
output="34"
scenario = Scenario(input, output)
part_02_scenarios = [scenario]
input="""T....#....
...T......
.T....#...
.........#
..#.......
..........
...#......
..........
....#.....
.........."""
output="9"
part_02_scenarios.append(scenario)